echo "\chapter{Network Reference Models and Protocols}" > "Mod1/chapters/1.1. Network Reference Models and Protocols.tex"
echo "\input{\"Mod1/chapters/1.1. Network Reference Models and Protocols.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"
echo "\chapter{Infrastructure Components}" > "Mod1/chapters/1.2. Infrastructure Components.tex"
echo "\input{\"Mod1/chapters/1.2. Infrastructure Components.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"
echo "\chapter{Network Architecture}" > "Mod1/chapters/1.3. Network Architecture.tex"
echo "\input{\"Mod1/chapters/1.3. Network Architecture.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"
echo "\chapter{Network Cabling}" > "Mod1/chapters/1.4. Network Cabling.tex"
echo "\input{\"Mod1/chapters/1.4. Network Cabling.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"
echo "\chapter{Basic Troubleshooting}" > "Mod1/chapters/1.5. Basic Troubleshooting.tex"
echo "\input{\"Mod1/chapters/1.5. Basic Troubleshooting.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"
echo "\chapter{IPv4 Addressing}" > "Mod1/chapters/1.6. IPv4 Addressing.tex"
echo "\input{\"Mod1/chapters/1.6. IPv4 Addressing.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"
echo "\chapter{IPv6 Addressing}" > "Mod1/chapters/1.7. IPv6 Addressing.tex"
echo "\input{\"Mod1/chapters/1.7. IPv6 Addressing.tex\"}" >> "Mod1/1. Fundamentals of Networking.tex"

echo "\chapter{Fundamentals of Ethernet}" > "Mod2/chapters/2.1. Fundamentals of Ethernet.tex"
echo "\input{\"Mod2/chapters/2.1. Fundamentals of Ethernet.tex\"}" >> "Mod2/2. LAN Switching.tex"
echo "\chapter{Basic Cisco Catalyst Switch Configuration}" > "Mod2/chapters/2.2. Basic Cisco Catalyst Switch Configuration.tex"
echo "\input{\"Mod2/chapters/2.2. Basic Cisco Catalyst Switch Configuration.tex\"}" >> "Mod2/2. LAN Switching.tex"
echo "\chapter{Virtual LANs (VLANs)}" > "Mod2/chapters/2.3. Virtual LANs (VLANs).tex"
echo "\input{\"Mod2/chapters/2.3. Virtual LANs (VLANs).tex\"}" >> "Mod2/2. LAN Switching.tex"
echo "\chapter{Trunking}" > "Mod2/chapters/2.4. Trunking.tex"
echo "\input{\"Mod2/chapters/2.4. Trunking.tex\"}" >> "Mod2/2. LAN Switching.tex"
echo "\chapter{Troubleshooting Switch Operation}" > "Mod2/chapters/2.5. Troubleshooting Switch Operation.tex"
echo "\input{\"Mod2/chapters/2.5. Troubleshooting Switch Operation.tex\"}" >> "Mod2/2. LAN Switching.tex"
echo "\chapter{Basic Switch Security}" > "Mod2/chapters/2.6. Basic Switch Security.tex"
echo "\input{\"Mod2/chapters/2.6. Basic Switch Security.tex\"}" >> "Mod2/2. LAN Switching.tex"
echo "\chapter{Voice VLANs}" > "Mod2/chapters/2.7. Voice VLANs.tex"
echo "\input{\"Mod2/chapters/2.7. Voice VLANs.tex\"}" >> "Mod2/2. LAN Switching.tex"

echo "\chapter{Basic Router Operation}" > "Mod3/chapters/3.1. Basic Router Operation.tex"
echo "\input{\"Mod3/chapters/3.1. Basic Router Operation.tex\"}" >> "Mod3/3. IP Routing.tex"
echo "\chapter{Basic Router Configuration and Verification}" > "Mod3/chapters/3.2. Basic Router Configuration and Verification.tex"
echo "\input{\"Mod3/chapters/3.2. Basic Router Configuration and Verification.tex\"}" >> "Mod3/3. IP Routing.tex"
echo "\chapter{Routing Fundamentals}" > "Mod3/chapters/3.3. Routing Fundamentals.tex"
echo "\input{\"Mod3/chapters/3.3. Routing Fundamentals.tex\"}" >> "Mod3/3. IP Routing.tex"
echo "\chapter{Routing Information Protocol (RIP)}" > "Mod3/chapters/3.4. Routing Information Protocol (RIP).tex"
echo "\input{\"Mod3/chapters/3.4. Routing Information Protocol (RIP).tex\"}" >> "Mod3/3. IP Routing.tex"

echo "\chapter{Dynamic Host Configuration Protocol (DHCP)}" > "Mod4/chapters/4.1. Dynamic Host Configuration Protocol (DHCP).tex"
echo "\input{\"Mod4/chapters/4.1. Dynamic Host Configuration Protocol (DHCP).tex\"}" >> "Mod4/4. Network Services.tex"
echo "\chapter{Network Address Translation (NAT)}" > "Mod4/chapters/4.2. Network Address Translation (NAT).tex"
echo "\input{\"Mod4/chapters/4.2. Network Address Translation (NAT).tex\"}" >> "Mod4/4. Network Services.tex"
echo "\chapter{Network Time Protocol (NTP)}" > "Mod4/chapters/4.3. Network Time Protocol (NTP).tex"
echo "\input{\"Mod4/chapters/4.3. Network Time Protocol (NTP).tex\"}" >> "Mod4/4. Network Services.tex"

echo "\chapter{Network Management Protocols}" > "Mod5/chapters/5.1. Network Management Protocols.tex"
echo "\input{\"Mod5/chapters/5.1. Network Management Protocols.tex\"}" >> "Mod5/5. Network Management.tex"
echo "\chapter{Device Management}" > "Mod5/chapters/5.2. Device Management.tex"
echo "\input{\"Mod5/chapters/5.2. Device Management.tex\"}" >> "Mod5/5. Network Management.tex"
echo "\chapter{Troubleshooting with Cisco IOS Tools}" > "Mod5/chapters/5.3. Troubleshooting with Cisco IOS Tools.tex"
echo "\input{\"Mod5/chapters/5.3. Troubleshooting with Cisco IOS Tools.tex\"}" >> "Mod5/5. Network Management.tex"
