#!/bin/bash
echo "\chapter{VLAN Trunking Protocol (VTP)}" > "Mod1/chapters/1.1. VLAN Trunking Protocol (VTP).tex"
echo "\input{\"Mod1/chapters/1.1. VLAN Trunking Protocol (VTP).tex\"}" >> "Mod1/1. LAN Switching.tex"
echo "\chapter{Spanning Tree Protocol (STP)}" > "Mod1/chapters/1.2. Spanning Tree Protocol (STP).tex"
echo "\input{\"Mod1/chapters/1.2. Spanning Tree Protocol (STP).tex\"}" >> "Mod1/1. LAN Switching.tex"
echo "\chapter{EtherChannel}" > "Mod1/chapters/1.3. EtherChannel.tex"
echo "\input{\"Mod1/chapters/1.3. EtherChannel.tex\"}" >> "Mod1/1. LAN Switching.tex"

echo "\chapter{Routing Between VLANs}" > "Mod2/chapters/2.1. Routing Between VLANs.tex"
echo "\input{\"Mod2/chapters/2.1. Routing Between VLANs.tex\"}" >> "Mod2/2. IP Routing.tex"
echo "\chapter{Open Shortest Path First (OSPF)}" > "Mod2/chapters/2.2. Open Shortest Path First (OSPF).tex"
echo "\input{\"Mod2/chapters/2.2. Open Shortest Path First (OSPF).tex\"}" >> "Mod2/2. IP Routing.tex"
echo "\chapter{Enhanced Interior Gateway Routing Protocol (EIGRP)}" > "Mod2/chapters/2.3. Enhanced Interior Gateway Routing Protocol (EIGRP).tex"
echo "\input{\"Mod2/chapters/2.3. Enhanced Interior Gateway Routing Protocol (EIGRP).tex\"}" >> "Mod2/2. IP Routing.tex"

echo "\chapter{Point-to-Point Protocol (PPP)}" > "Mod3/chapters/3.1. Point-to-Point Protocol (PPP).tex"
echo "\input{\"Mod3/chapters/3.1. Point-to-Point Protocol (PPP).tex\"}" >> "Mod3/3. Wide Area Networks (WANs).tex"
echo "\chapter{Options for WAN Connectivity}" > "Mod3/chapters/3.2. Options for WAN Connectivity.tex"
echo "\input{\"Mod3/chapters/3.2. Options for WAN Connectivity.tex\"}" >> "Mod3/3. Wide Area Networks (WANs).tex"
echo "\chapter{WAN Topologies}" > "Mod3/chapters/3.3. WAN Topologies.tex"
echo "\input{\"Mod3/chapters/3.3. WAN Topologies.tex\"}" >> "Mod3/3. Wide Area Networks (WANs).tex"
echo "\chapter{Border Gateway Protocol (BGP)}" > "Mod3/chapters/3.4. Border Gateway Protocol (BGP).tex"
echo "\input{\"Mod3/chapters/3.4. Border Gateway Protocol (BGP).tex\"}" >> "Mod3/3. Wide Area Networks (WANs).tex"

echo "\chapter{Hot Standby Router Protocol (HSRP)}" > "Mod4/chapters/4.1. Hot Standby Router Protocol (HSRP).tex"
echo "\input{\"Mod4/chapters/4.1. Hot Standby Router Protocol (HSRP).tex\"}" >> "Mod4/4. Network Services.tex"
echo "\chapter{Quality of Service (QoS)}" > "Mod4/chapters/4.2. Quality of Service (QoS).tex"
echo "\input{\"Mod4/chapters/4.2. Quality of Service (QoS).tex\"}" >> "Mod4/4. Network Services.tex"
echo "\chapter{Cloud Resources}" > "Mod4/chapters/4.3. Cloud Resources.tex"
echo "\input{\"Mod4/chapters/4.3. Cloud Resources.tex\"}" >> "Mod4/4. Network Services.tex"

echo "\chapter{Advanced Switch Security}" > "Mod5/chapters/5.1. Advanced Switch Security.tex"
echo "\input{\"Mod5/chapters/5.1. Advanced Switch Security.tex\"}" >> "Mod5/5. Securing Network Devices.tex"
echo "\chapter{Access Control Lists (ACLs)}" > "Mod5/chapters/5.2. Access Control Lists (ACLs).tex"
echo "\input{\"Mod5/chapters/5.2. Access Control Lists (ACLs).tex\"}" >> "Mod5/5. Securing Network Devices.tex"

echo "\chapter{Network Management Protocols}" > "Mod6/chapters/6.1. Network Management Protocols.tex"
echo "\input{\"Mod6/chapters/6.1. Network Management Protocols.tex\"}" >> "Mod6/6. Network Management.tex"
echo "\chapter{Network Programmability}" > "Mod6/chapters/6.2. Network Programmability.tex"
echo "\input{\"Mod6/chapters/6.2. Network Programmability.tex\"}" >> "Mod6/6. Network Management.tex"
